version: "3.8"

services:

  catalogue_service:
    image: tamarar/ci-demo:latest
    container_name: catalogue_service
    hostname: catalogue_service
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      CATALOGUE_SERVICE_ADDRESS: :${PORT}
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}
    depends_on:
      - jaeger
    # networks:
    #   - network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    # networks:
    #   - network

# networks:
#   network:
#     driver: bridge