version: "3.8"

services:

  product_service:
    image: tamarar/ci-demo:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: product_service
    hostname: product_service
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PRODUCT_SERVICE_ADDRESS: :${PORT}
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"